/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as IcPersonRouteImport } from './routes/ic.$person'
import { Route as IcPersonIndexRouteImport } from './routes/ic.$person.index'
import { Route as IcPersonPersonalRouteImport } from './routes/ic.$person.personal'
import { Route as IcPersonTeamRouteImport } from './routes/ic.$person.team'
import { Route as PortalCustomIndexRouteImport } from './routes/portal_.custom.index'
import { Route as PortalCustomNameRouteImport } from './routes/portal_.custom.$name'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const IcPersonRoute = IcPersonRouteImport.update({
  id: '/ic/$person',
  path: '/ic/$person',
  getParentRoute: () => rootRouteImport,
} as any)
const IcPersonIndexRoute = IcPersonIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IcPersonRoute,
} as any)
const IcPersonPersonalRoute = IcPersonPersonalRouteImport.update({
  id: '/personal',
  path: '/personal',
  getParentRoute: () => IcPersonRoute,
} as any)
const IcPersonTeamRoute = IcPersonTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => IcPersonRoute,
} as any)
const PortalCustomIndexRoute = PortalCustomIndexRouteImport.update({
  id: '/portal_/custom/',
  path: '/portal/custom/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalCustomNameRoute = PortalCustomNameRouteImport.update({
  id: '/portal_/custom/$name',
  path: '/portal/custom/$name',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/portal': typeof PortalRoute
  '/ic/$person': typeof IcPersonRouteWithChildren
  '/ic/$person/personal': typeof IcPersonPersonalRoute
  '/ic/$person/team': typeof IcPersonTeamRoute
  '/portal/custom/$name': typeof PortalCustomNameRoute
  '/ic/$person/': typeof IcPersonIndexRoute
  '/portal/custom/': typeof PortalCustomIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/portal': typeof PortalRoute
  '/ic/$person/personal': typeof IcPersonPersonalRoute
  '/ic/$person/team': typeof IcPersonTeamRoute
  '/portal/custom/$name': typeof PortalCustomNameRoute
  '/ic/$person': typeof IcPersonIndexRoute
  '/portal/custom': typeof PortalCustomIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/portal': typeof PortalRoute
  '/ic/$person': typeof IcPersonRouteWithChildren
  '/ic/$person/personal': typeof IcPersonPersonalRoute
  '/ic/$person/team': typeof IcPersonTeamRoute
  '/portal_/custom/$name': typeof PortalCustomNameRoute
  '/ic/$person/': typeof IcPersonIndexRoute
  '/portal_/custom/': typeof PortalCustomIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/portal'
    | '/ic/$person'
    | '/ic/$person/personal'
    | '/ic/$person/team'
    | '/portal/custom/$name'
    | '/ic/$person/'
    | '/portal/custom/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/portal'
    | '/ic/$person/personal'
    | '/ic/$person/team'
    | '/portal/custom/$name'
    | '/ic/$person'
    | '/portal/custom'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/portal'
    | '/ic/$person'
    | '/ic/$person/personal'
    | '/ic/$person/team'
    | '/portal_/custom/$name'
    | '/ic/$person/'
    | '/portal_/custom/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  PortalRoute: typeof PortalRoute
  IcPersonRoute: typeof IcPersonRouteWithChildren
  PortalCustomNameRoute: typeof PortalCustomNameRoute
  PortalCustomIndexRoute: typeof PortalCustomIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ic/$person': {
      id: '/ic/$person'
      path: '/ic/$person'
      fullPath: '/ic/$person'
      preLoaderRoute: typeof IcPersonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ic/$person/': {
      id: '/ic/$person/'
      path: '/'
      fullPath: '/ic/$person/'
      preLoaderRoute: typeof IcPersonIndexRouteImport
      parentRoute: typeof IcPersonRoute
    }
    '/ic/$person/personal': {
      id: '/ic/$person/personal'
      path: '/personal'
      fullPath: '/ic/$person/personal'
      preLoaderRoute: typeof IcPersonPersonalRouteImport
      parentRoute: typeof IcPersonRoute
    }
    '/ic/$person/team': {
      id: '/ic/$person/team'
      path: '/team'
      fullPath: '/ic/$person/team'
      preLoaderRoute: typeof IcPersonTeamRouteImport
      parentRoute: typeof IcPersonRoute
    }
    '/portal_/custom/': {
      id: '/portal_/custom/'
      path: '/portal/custom'
      fullPath: '/portal/custom/'
      preLoaderRoute: typeof PortalCustomIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal_/custom/$name': {
      id: '/portal_/custom/$name'
      path: '/portal/custom/$name'
      fullPath: '/portal/custom/$name'
      preLoaderRoute: typeof PortalCustomNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface IcPersonRouteChildren {
  IcPersonPersonalRoute: typeof IcPersonPersonalRoute
  IcPersonTeamRoute: typeof IcPersonTeamRoute
  IcPersonIndexRoute: typeof IcPersonIndexRoute
}

const IcPersonRouteChildren: IcPersonRouteChildren = {
  IcPersonPersonalRoute: IcPersonPersonalRoute,
  IcPersonTeamRoute: IcPersonTeamRoute,
  IcPersonIndexRoute: IcPersonIndexRoute,
}

const IcPersonRouteWithChildren = IcPersonRoute._addFileChildren(
  IcPersonRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  PortalRoute: PortalRoute,
  IcPersonRoute: IcPersonRouteWithChildren,
  PortalCustomNameRoute: PortalCustomNameRoute,
  PortalCustomIndexRoute: PortalCustomIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
